plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'org.almanac'
version = '1.0.0'

android {
  namespace "org.almanac.health"
  defaultConfig {
    versionCode 1
    versionName '1.0.0'
    minSdkVersion 26
  }
}

dependencies {
  // Health Connect: sleep sessions written by Samsung Health, Fitbit, etc.
  implementation "androidx.health.connect:connect-client:1.1.0"
}
